
package com.totaplay.searchONT.tprovisioningSoa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-14T19:56:28.447-06:00
 * Generated source version: 3.5.0
 *
 */
public final class TProvisioningSoap_TProvisioningSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "TProvisioning");

    private TProvisioningSoap_TProvisioningSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TProvisioning.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TProvisioning ss = new TProvisioning(wsdlURL, SERVICE_NAME);
        TProvisioningSoap port = ss.getTProvisioningSoap12();

       
        
        {
        System.out.println("Invoking getSearchONTDash...");
        java.lang.String _getSearchONTDash_strvalue = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT _getSearchONTDash__return = port.getSearchONTDash(_getSearchONTDash_strvalue);
        System.out.println("getSearchONTDash.result=" + _getSearchONTDash__return);


        }
      
       
        {
        System.out.println("Invoking getSearchONT...");
        java.lang.String _getSearchONT_strvalue = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT _getSearchONT__return = port.getSearchONT(_getSearchONT_strvalue);
        System.out.println("getSearchONT.result=" + _getSearchONT__return);


        }
       

        System.exit(0);
    }

}
